Feature/1
CDS-Mobile1/CDS_Server pull request #2
Opened 2023-05-16 19:14 UTC by jiyeoon00

## 🖇 Related Issue
- close #1 

## ✏️ Contents
- member entity 구현 및 고정 멤버(id=1) 찾아오기 구현
- post, postImage entity 구현 및 게시물 생성 기능 구현

## 📝 PR Point
- 데이터 값 따로 없을 시 null 값 주지 말고 아예 필드 주지 말자고 했는데, 그렇게 하려면 지금 response 줄 때 공통으로 쓰고 있는 ApiResponseDto말고 따로 하나 더 만드는 게 좋을까?!

## 📷 Screenshot

2023-05-17 06:33 UTC, yeseul106 commented
다음 PR 부터는 리뷰어에 저 태그해주세요 ! 🥰

2023-05-17 08:49 UTC, yeseul106 requested changes
고생하셨씁니다 !! 코드리뷰 확인 부탁드려요 :)

2023-05-17 08:49 UTC, yeseul106 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/dto/ApiResponseDto.java
> +@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
p5;

이런 것 static import로 해서 간결하게 표현할 수 있을 것 같습니다 !

2023-05-17 08:49 UTC, yeseul106 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/dto/ApiResponseDto.java
> +@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
p3;

PR point에 적어두신 것 관련해서 답변 드립니다 !

현재 ApiResponseDto에 멤버 변수로 가지고 있는 data 필드는 final 키워드가 붙어있지 않기 때문에 이 RequiredArgConstructor 어노테이션이 해당 필드를 제외한 생성자를 만들어 줍니다. 따라서 20줄에 정의되어 있는 success 메소드를 사용하면 data가 안담기는 response body를 내려줄 수 있을 것 같습니다 !!

2023-05-17 08:49 UTC, yeseul106 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/member/domain/Member.java
> +    private String profileUrl;
p3;

현재 Member 엔티티 안에 profileUrl 필드가 옵셔널이기 때문에 생성 패턴 builder 써도 좋을 것 같은데 혹시 어떻게 생각하시는지 궁금해요 :) 
그리고 현재 기본 생성자 밖에 정의가 안되어있는 것 같은데 이거 문제없이 객체 만들어지나요 ?

2023-05-17 08:49 UTC, yeseul106 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/domain/Post.java
> +@Builder
p4;

클래스 위에 Builder 어노테이션을 붙이면 @AllArgsConstructor을 반드시 붙여줘야하는데 사실 @AllArgsConstructor는 꼭 필요한 경우가 아니고선 쓰는 것을 지양합니다. 그래서 빌더패턴 쓸 때 아래와 같이 생성자를 직접 만들어주고 그 위에 @Builder 어노테이션을 붙여주는 것이 좋을 것 같아요 !

2023-05-17 08:49 UTC, yeseul106 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/domain/Post.java
> +}
p3;

위에 리뷰 달아드린 @Builder를 아래와 같이 생성자 만들어서 거기에 직접 달아주는 것이 좋을 것 같아요 !

```suggestion
     @Builder
     public Post (Member member, String content) {
         this.member = member;
         this.content = content;
     }

}

```

2023-05-17 08:49 UTC, yeseul106 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/domain/PostImage.java
> +    public PostImage(Post post, String url) {
p4;

모든 entity 일괄적으로 builder 패턴 적용하는 것이 헷갈리지 않을 것 같습니다 !

2023-05-17 08:51 UTC, yeseul106 commented
PR point 두번째 관련해서는, 현재는 s3 연결까지는 하지 않으니까 지금 단계에서는 쓰는 경우 없을것 같지만 추후 개발 확장성을 생각 했을 때 클라분들이 null 값 보내시면 기본이미지 우리 s3에 저장해놓은거 내려주는 것 좋을 거 같아요 ! 😀

2023-05-17 09:26 UTC, yeseul106 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/dto/ApiResponseDto.java
> +public class ApiResponseDto<T> {
PR point 첫번째는 다음 어노테이션을 ApiResponseDto 클래스에 붙여주면 해당 값이 null일 때는 프로퍼티를 제외하고 내려줄 수 있습니다 !

```suggestion
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ApiResponseDto<T> {

```

2023-05-17 11:52 UTC, jiyeoon00 reviewed
리뷰 확인 완료했습니다~~

2023-05-17 11:52 UTC, jiyeoon00 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/dto/ApiResponseDto.java
> +public class ApiResponseDto<T> {
오 이런 어노테이션이 있군요?!

2023-05-17 11:52 UTC, jiyeoon00 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/member/domain/Member.java
> +    private String profileUrl;
현재 고정멤버(id=1) 인 멤버만 가져오는 거라 member 객체를 만들 일이 없어서 안 만들었어요! 만든다면 예슬님 말씀처럼 옵셔널 필드가 있어서 일일이 null값을 넘겨줘야 하는 경우가 생기기 때문에 builder패턴이 좋아보입니다~!

2023-05-17 11:52 UTC, jiyeoon00 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/domain/PostImage.java
> +    public PostImage(Post post, String url) {
네넵 통일 시키는 게 좋을 것 같네요!

2023-05-17 11:52 UTC, jiyeoon00 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/domain/Post.java
> +@Builder
@builder를 메소드에 달아주면 @AllArgsConstructor을 굳이 안 붙여도 되겠군요! 적용하겠습니다~!

2023-05-17 11:55 UTC, yeseul106 approved these changes

2023-05-17 11:55 UTC, merged

2023-05-18 11:46 UTC, yeseul106 commented on Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/dto/ApiResponseDto.java
> +    public static ApiResponseDto success(SuccessStatus successStatus) {
p4;

근데 제가 저번에 잠을 안잔 상태로 리뷰해서 약간 정신 못차렸었는데...ㅎㅎㅎ
여기 보면 PR Point 첫번째에 말씀하신 data를 내려보내주지 않아도 될 때, 요 success 정적 팩토리 메소드로 ApiResponseDto 객체 만들면 될 것 같아요 ! 그럼 json 형식의 response body에 data 프로퍼티 없이 code, success, message만 내려줄 수 있겠네요 !!